name: app
description: A Marvel heroes app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  get_it: ^7.6.0
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  crypto: ^3.0.3
  expandable: ^5.0.1
  flutter_i18n: ^0.32.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    - assets/i18n/